name: Scrape Fishing Reports

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: List files for debugging
      run: ls -R
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python automated_scraping/scripts/scraper.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Update fishing reports data" || echo "No changes to commit"
        git push